name: Checks
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}
permissions:
  checks: write
  contents: read
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version: 1.23.2
      - name: Install govulncheck
        run: go install github.com/google/addlicense@latest
      - name: check license headers
        run: >
          if [[ $(addlicense --check -- src/ | wc -c) -ne 0 ]]; then
              addlicense --check -- src/
              exit 1
          else
              echo "license check succeeded."
          fi
